version: 2

sources:
  - name: raw
    schema: RAW
    description: Greenweez data source
    tables:
    - name: sales
      identifier: SALES
      description: sales of greenweez
      columns:
        - name: orders_id
          description: Primary key of the table
          tests:
            - unique
            - not_null
    - name: product
      identifier: PRODUCT
      description: products and purchase price of Greenweez
      columns:
        - name: products_id
          description: the ID of the products on Greenweez | Primary key of the table
          tests:
            - unique
            - not_null
    - name: ship
      identifier: SHIP
      columns:
        - name: orders_id
          description: Primary key of the table
          tests:
            - unique
            - not_null