version: 2

sources:
  - name: raw
    schema: RAW
    tables:
    - name: sales
      identifier: SALES
    - name: product
      identifier: PRODUCT
    - name: ship
      identifier: SHIP
  